name: Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  setup:
    runs-on: windows-2019
    defaults:
      run:
        shell: cmd
        working-directory: php-sdk
    env:
      PHP_SDK_VS: vs16

    steps:
#       - uses: ilammy/msvc-dev-cmd@v1
      - uses: actions/checkout@v2
        with:
          repository: Microsoft/php-sdk-binary-tools
          ref: php-sdk-2.2.0
          path: php-sdk

      - run: phpsdk-vs16-x64.bat
#       - run: echo "::add-path::%GITHUB_WORKSPACE%\php-sdk\bin"

#       - run: bin\phpsdk_buildtree.bat phpmaster

#       - run: |
#           git status
#           Get-ChildItem -Depth 2
#         shell: powershell
#         working-directory: php-sdk\phpmaster\vs16

      - uses: actions/checkout@v2
        with:
          repository: php/php-src
          ref: php-8.0.0alpha1
          path: php-src

#       - run: ..\php-sdk\bin\phpsdk_deps --update --branch master
#         working-directory: php-src
#         env:
#           PHP_SDK_VS: vs16

#       - run: |
#           git status
#           Get-ChildItem -Depth 1
#         shell: powershell
#         working-directory: php-sdk

#       - run: |
#           git status
#           Get-ChildItem -Depth 1
#         shell: powershell
#         working-directory: php-src

#   compile:
#     runs-on: windows-2019
#     needs: [setup]

#     steps:
#       - run: phpsdk-vs16-x64.bat
      - run: |
          buildconf
          configure --help
        working-directory: php-src
#       - run: configure --help
#         working-directory: php-src
      - run: configure --enable-cli
#       - run: configure --disable-all --enable-cli --enable-$remains
        working-directory: php-src
      - run: nmake
        working-directory: php-src
      - uses: actions/upload-artifact@v2
        with:
          name: php
          path: php-src/Release_TS
