name: Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  setup:
    runs-on: windows-2019
    defaults:
      run:
        shell: cmd
        working-directory: php-sdk

    steps:
    - uses: actions/checkout@v2
      with:
        repository: Microsoft/php-sdk-binary-tools
        path: php-sdk

    - run: Get-ChildItem -Depth 1
      shell: powershell

    - run: phpsdk-vs16-x64.bat
    - run: echo "::add-path::${{ env.GITHUB_WORKSPACE }}\bin"

    - run: |
        git status
        Get-ChildItem -Depth 1
      shell: powershell

    - run: phpsdk_buildtree phpdev

    - run: |
        git status
        Get-ChildItem -Depth 2
      shell: powershell
      working-directory: php-sdk\phpdev\vs16

    - uses: actions/checkout@v2
      with:
        repository: php/php-src
        ref: php-8.0.0alpha1
        path: php-src

    - run: phpsdk_deps -u
      working-directory: php-src

    - run: |
        git status
        Get-ChildItem -Depth 1
      shell: powershell
      working-directory: php-src
