name: Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019
    defaults:
      run:
        shell: cmd
        working-directory: php-sdk

    steps:
#     - uses: actions/checkout@v2
#       with:
#         repository: php/php-src
#         path: php
    - uses: actions/checkout@v2
      with:
        repository: Microsoft/php-sdk-binary-tools
        path: php-sdk

    - run: Get-ChildItem -Depth 1
      shell: powershell

    - run: phpsdk-vs16-x64.bat

    - run: Get-ChildItem -Depth 1
      shell: powershell

    - run: phpsdk_buildtree phpdev

    - run: Get-ChildItem -Depth 1
      shell: powershell
