name: Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  setup:
    runs-on: windows-2019
    defaults:
      run:
        shell: cmd
        working-directory: php-sdk

    steps:
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: actions/checkout@v2
      with:
        repository: Microsoft/php-sdk-binary-tools
        path: php-sdk

    - run: Get-ChildItem -Depth 1
      shell: powershell

    - run: phpsdk-vs16-x64.bat
    - run: echo "::add-path::%GITHUB_WORKSPACE%\php-sdk\bin"

    - run: |
        git status
        Get-ChildItem -Depth 1
      shell: powershell

    - run: bin\phpsdk_buildtree.bat phpmaster

    - run: |
        git status
        Get-ChildItem -Depth 2
      shell: powershell
      working-directory: php-sdk\phpmaster\vs16

    - uses: actions/checkout@v2
      with:
        repository: php/php-src
#         ref: php-8.0.0alpha1
        path: php-src

    - run: ..\php-sdk\bin\phpsdk_deps --update --branch master
      working-directory: php-src
      env:
        PHP_SDK_VS: vs16

    - run: |
        git status
        Get-ChildItem -Depth 1
      shell: powershell
      working-directory: php-src
