name: Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019
    defaults:
      run:
        working-directory: c:\php-sdk

    steps:
#     - uses: actions/checkout@v2
#       with:
#         repository: php/php-src
#         path: php
    - uses: actions/checkout@v2
      with:
        repository: Microsoft/php-sdk-binary-tools
        path: c:\php-sdk

    - run: Get-ChildItem -Depth 1
    
    - run: Start-Process phpsdk-vs16-x64.bat
