name: Mac
# https://zenn.dev/hgsgtk/articles/fb9af8bfc64ec37bce2d

on:
  workflow_dispatch:
  push:
    paths: .github/workflows/mac.yml

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15]
        php: [master]

    steps:
      - uses: actions/checkout@v2
        with:
          repository: php/php-src
          ref: ${{ matrix.php }}
      - run: ls -la
      - run: brew list
