name: Ubuntu

on:
  workflow_dispatch:
  push:
    paths: .github/workflows/ubuntu.yml

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
        php: [php-7.4.8, php-8.0.0alpha3]

    steps:
      - uses: actions/checkout@v2
        with:
          repository: php/php-src
          ref: ${{ matrix.php }}
      - run: ls -la
      - run: apt list pkg-config build-essential autoconf bison re2c libxml2-dev libsqlite3-dev
      - run: sudo apt install -y autoconf re2c libxml2-dev
      - run: apt list pkg-config build-essential autoconf bison re2c libxml2-dev libsqlite3-dev
      - run: ./buildconf
      - run: ls -la
      - run: ./configure
      - run: ls -la
      - run: make -j4
      - run: ls -la
      - run: git status
